// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcCco4GoQu2CUH8KFHv4-Bw0plgwOxOOY',
    appId: '1:1002530083515:android:0c0be6aef0ba4c0f324f9e',
    messagingSenderId: '1002530083515',
    projectId: 'asiet-calendar-app',
    databaseURL: 'https://asiet-calendar-app-default-rtdb.firebaseio.com',
    storageBucket: 'asiet-calendar-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBquTfYt0DiKVBCMCBB64Y6ykNo0PkaWXA',
    appId: '1:1002530083515:ios:6c0afb6c1db36c7d324f9e',
    messagingSenderId: '1002530083515',
    projectId: 'asiet-calendar-app',
    databaseURL: 'https://asiet-calendar-app-default-rtdb.firebaseio.com',
    storageBucket: 'asiet-calendar-app.appspot.com',
    androidClientId: '1002530083515-eratm8p4oo852o027udo1m68b05alair.apps.googleusercontent.com',
    iosClientId: '1002530083515-3sq1t69i4ej3i722frlvf4epvkpndj7e.apps.googleusercontent.com',
    iosBundleId: 'com.asiet.calendar.calendarApp',
  );

}